name: webpage
on:
    push:
        branches:
            - main

jobs:
    build:
        uses: ugognw/pchemdb/.github/workflows/docs.yml@main
    # Deployment job
    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: github.repository == 'ugognw/pchemdb'
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
