name: testing
on:
    push:
    pull_request:
        branches:
            - $default-branch

defaults:
  run:
    shell: bash

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: '3.11'
          - name: Install Hatch
            uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc
          - name: Run tests
            run: |
              hatch run test-cov
          - uses: codecov/codecov-action@v5
            with:
              fail_ci_if_error: true
              flags: unittests # optional
              name: codecov-umbrella # optional
              token: ${{ secrets.CODECOV_TOKEN }}
              verbose: true
